### ISSUE TITLE
交朋友

### ISSUE THREAD

**Issue by tianting12** [zhang-jc/zhang-jc.github.io#1]
hi，我看了你的hue编译的问题。我想问你下问题

关于npm安装，

**Comment by zhang-jc** [comment]
> hi，我看了你的hue编译的问题。我想问你下问题
> 
> 关于npm安装，

非常抱歉，这个项目是我基于hexo搭建的个人博客。一直没看你提交的消息。

**Comment by zhang-jc** [comment]
@tianting12 非常抱歉，这个项目是我基于hexo搭建的个人博客。一直没看你提交的消息。
